baseurl = "https://example.com/"
languageCode = "en-US"
title = "R Ladies - Seattle"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "seattle.jpg"
  author = "R Ladies - Seattle"
  description = "R Ladies - Seattle Blogdown Site"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "rladies-seattle"
  Email         = "email@example.com"
  Twitter       = "RLadiesSeattle"
  Slack         = "rladies-sea"
  Meetup        = "https://www.meetup.com/rladies-seattle/"

## Main Menu
[[menu.main]]
  name = "events"
  weight = 100
  identifier = "events"
  url = "https://www.meetup.com/rladies-seattle/"
[[menu.main]]
  name = "info"
  identifier = "info"
  weight = 200
  url = "/info/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 300
  url = "/projects/"
